services:
  rest:
    build: ./rest
    restart: always
    ports:
      - 5000:5000
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=questions
  db:
    image: postgres
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=questions
    volumes:
      - ~/question_data:/var/lib/postgresql/data
      - ./rest/schema.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: question_db
